<a href="https://colab.research.google.com/github/ChauHungCheungCyrus/CyrusSmallProject/blob/main/BasePython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv

%precision 2

with open("mpg.csv") as csvfile:
  mpg = list(csv.DictReader(csvfile))

mpg[:3]


[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [ ]:
len(mpg) #check how many dict we have

234

In [ ]:
mpg[0].keys()#check the variable of the csvfile

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

**Find average cty fuel economy around all cars**

In [ ]:
sum(float(d["cty"])for d in mpg) / len(mpg)

16.86

**Find average hwy fuel economy around all cars**

In [ ]:
sum(float(d["hwy"])for d in mpg) / len(mpg)

23.44

Grouping the cars by number of cylinder and finding the average cty mpg for each group (Example1)

In [ ]:
cylinders = set(d["cyl"]for d in mpg)

In [ ]:
CtyMpgByCyl = []

for c in cylinders:
  sum = 0
  count = 0
  for d in mpg:
    if d['cyl'] == c:
      sum += float(d["cty"]) #add the cty mpg
      count += 1
  CtyMpgByCyl.append((c, sum/ count)) #append tuple2 the list

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

Example2

In [ ]:
vehicleclass = set(d["class"] for d in mpg) #what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [ ]:
HwyMpgByClass = []

for t in vehicleclass:
  sum = 0
  count = 0
  for d in mpg:
    if d["class"] == t:
      sum += float(d["hwy"])
      count += 1
  HwyMpgByClass.append(t, sum/ count) #tuple("class", "avg mpg")

HwyMpgByClass.sort(key=lambda x : x[1])
HwyMpgByClass

Datas and Times


In [ ]:
import datetime as dt
import time as tm

In [ ]:
tm.time()

1718021416.2410917

In [ ]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2024, 6, 10, 12, 11, 12, 52295)

get the data from a datatime

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2024, 6, 10, 12, 11, 12)

Find the 100 days ago

In [ ]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(days=100)

In [ ]:
today = dt.date.today()

In [ ]:
today - delta

datetime.date(2024, 3, 2)

Test it

In [ ]:
today > today - delta

True

Very basical Python OOP

In [ ]:
class Person:
  department = "School of Engineering"

  def set_name(self, new_name):
    self.name = new_name

  def set_location(self, new_location):
    self.location = new_location

In [ ]:
person = Person()
person.set_name("Cheu Hung Cheung, Cyrus")
person.set_location("Hong Kong")
print("{} live in {} and works in the department {}".format(person.name, person.location, person.department))

Cheu Hung Cheung, Cyrus live in Hong Kong and works in the department School of Engineering


Map function

In [ ]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [ ]:
for i in cheapest:
  print(i)

9.0
11.0
12.34
2.01


Lambda Function

In [ ]:
my_function = lambda a, b, c: a + b
my_function(1, 2, 3)

3

Numpy_ed

In [ ]:
import numpy as np
import math

Array Creation

In [ ]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim)# finding the dumension of the list

[1 2 3]
1


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)# finding the dumension of the list

[[1 2 3]
 [4 5 6]]
2


In [ ]:
b.shape

(2, 3)

In [ ]:
b.dtype #check the type of the array

dtype('int64')